### ISSUE TITLE
huge dips in data being sent to graphite

### ISSUE THREAD

**Issue by jveldboom** [spilgames/mysql-statsd#29]
First thank you for this great way to send stats.

I'm having some issues with all my graphs in Graphite having huge dips in the data. Here's a sample of two showing data from a 15min period.

![select](https://cloud.githubusercontent.com/assets/303202/5609256/fd2e4500-9469-11e4-92cf-0deb406015a1.png) ![render 1](https://cloud.githubusercontent.com/assets/303202/5609217/c9022e0a-9468-11e4-9ce1-81fd3912d87f.png)

I checked the raw data through the `rawData=true` command and it confirms the data not being consistent.

9299850.3
9300506.3
9301359.7
**8371844.9**
9302794.1
9303719.2
9304351.2

Any idea what is causing this and how I can fix it?

Thanks!

**Comment by art-spilgames** [comment]
Hi John,

Thanks for using mysql_statsd!
Are you sending the data as a gauge, raw or as a delta?
The com_select is an ever increasing number in MySQL so sending it as raw will work in most cases, but to calculate it back to a rate will require you to apply a non-negative derivative. However if you seek for this metric as an ever increasing number it is adviced to be sent as a gauge. Gauge will keep the last stored value until it receives a different value, while a normal metric takes the average of all sent values.

If the sending is exactly the same rate (once per every second) as your statsd daemon sends it (once per 10 seconds by default) to your graphite cluster it works out in most of the cases. However sometimes the timing will be a few milliseconds off and you will miss a beat. Then the statsd daemon will average 9 values over 10 seconds the rate drops.

This is why we introduced the delta value where it stores the last known value in memory and subtracts that from the previously known value and only sends the delta to the statsd daemon. You might still miss a beat in sending metrics, but the average drop is less steep as with the raw value.

I see our example configuration wasn't updated in the latest release, so I'll fix that today. At least this is the release:
https://github.com/spilgames/mysql-statsd/compare/mysql-statsd-0.1.2...master
You can change the raw values to delta by changing the r to d.

Does this fix your issue?

**Comment by jveldboom** [comment]
Thank you for the thorough explanation. I changed the values to delta and it seemed to immediately fixed the issue. I've had it running for about half a day and it seems to be working just as expected. I'll comment back here if there's any further issues.

On a side note, do you want some help with the documentation? This likely has to do with my limited knowledge of nodejs, statsd and python, but I has to do some digging to get it to work. I've install mysql-statsd on a handful of Ubuntu 14.04 machines today so would be fairly familiar with all the steps needed to get it up and running.

I would also mention how the configuration file works. I was not totally aware that I could change the metics in the config file - like adding new ones. Again - this is likely a noob issue, but thought it might helpful to mention it how it can be adjusted.

I would love to help with this great project so please let me know what I can do.

Thanks again!

**Comment by art-spilgames** [comment]
Good to hear your issue has been resolved now!
I have extended the documentation with a config file section, so I hope everything is clear after my colleagues have merged the pull request. But you are more than welcome to help our with the documentation. :+1:

**Comment by jveldboom** [comment]
Still not sure I'm doing this right or using the write date type. I changed the "com_"s to deltas, but noticed some decimal numbers where being sent.

For example the graph below is showing some test queries I ran on the machine. I would expect these numbers to be whole numbers. But is this due to the way statsd is averaging them?

![image](https://cloud.githubusercontent.com/assets/303202/5635951/9a038ec4-95bb-11e4-9b0e-7ba883366c0c.png)

I think switching to the gauge type will fix this issue, but I wanted to check with you first since your update documentation specifically said these com_ values should be delta types.

**Comment by art-spilgames** [comment]
Hi,

Sorry for the late reply. Yes StatsD will average out the number of queries as it is a rate (so queries per second). That means you can get fractions in the end result.
On the flip side if you stick to a gauge you will only see an ever increasing graph, or if you apply the integral function of Graphite a similar rate graph like this one.

Art

**Comment by thijsdezoete** [comment]
I think we can close this issue now
(will close it next week if no one else replies)

**Comment by jveldboom** [comment]
Yes, thanks for your great support guys!
